### ISSUE TITLE
How to stop contract deployment?

### ISSUE THREAD

**Issue by saitam1** [parity-js/shell#154]
I'm running:

        Parity client version: v1.10.8-stable-bd20c45-20180628/x86_64-linux-gnu/rustc1.27.0
        Parity UI version: 0.1.4
        Operating system: Linux
        Installed via: .deb file
        Fully synchronized: Yes
        Network: Kovan
        I tried to restart both Parity UI and Parity Ethereum client: Yes

A contract is being deployed for 1 hour. How can I stop the process? It is not shown as pending in transactions and also I can't click any option in the `will deploy a contract` popup. Trying to do a simple eth transaction afterwards doesnt work either, because the contract deployment is not done.

This is all I see:
[https://imgur.com/a/hDPQHjs](https://imgur.com/a/hDPQHjs)

**Comment by Tbaut** [comment]
For such problems, please join our support channel: https://gitter.im/paritytech/parity as it is most of the time easier to troubleshoot directly.

You transaction to deploy the contract is preventing other transactions to be included into blocks (due to the nonce being higher). You could launch parity node with `--no-persistent-txqueue` to remove the pending transaction that blocks others. It is important to understand why it got stuck though -> your other issue.
