### ISSUE TITLE
Trouble connecting Parity to MetaMask

### ISSUE THREAD

**Issue by john-light** [parity-js/shell#202]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity client version**: 2.0.1-20180726-beta
> - **Parity UI version**: 0.3.4
> - **Operating system**: Linux
> - **Installed via**: .deb file
> - **Fully synchronized**: yes
> - **Network**: ethereum
> - **I tried to restart both Parity UI and Parity Ethereum client**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

See this issue for related commentary:

https://github.com/MetaMask/metamask-extension/issues/5098#issuecomment-416475237

I tried to follow the instructions in MetaMask documentation to connect Parity to MetaMask and was not able to connect. Folks on the MetaMask side tried to help but I'm still having issues. Am hoping someone in the Parity community can step in to help on this issue or over on the MetaMask issue.

**Comment by Tbaut** [comment]
I answered in the MM repo, but here it is:
Since Parity only allows local HTTP RPC per default, you need to specifically whitelist the domain used by Metamask using the flag `jsonrpc-cors`. The domain used can be figured out by opening Metamask in a new tab (top right icon in the beta version). You will find the domain in the address bar. I have it working on firefox using `parity --chain kovan --jsonrpc-cors moz-extension://ae62fc16-c916-4c24-9a36-97f5a850f25c`

BTW this is not a question related to Parity UI, the correct repo would be parity-ethereum.

**Comment by john-light** [comment]
@Tbaut Thanks! As I run Parity using Parity-UI and was hoping I could configure Parity to properly connect to MetaMask through the UI I was hoping this might be the right place. Should I open a new issue with a feature request to make it so users can adjust these settings in Parity UI?

**Comment by john-light** [comment]
Addendum, can move to a new issue if needed but it's related to this one. When I run the recommended command (pointing at MetaMask in Chromium rather than Firefox as given in the example) I get the following response:

```
parity --chain mainnet --jsonrpc-cors chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn
Database was created with newer client version. Upgrade your client or delete DB and resync.
```

So I update both Parity and Parity UI, to which the response is:

```
parity is already the newest version (1.11.8).
Calculating upgrade... Done
```

and

```
parity-ui is already the newest version (0.3.4).
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
I re-run the recommended command and still get the following error message in response:

```
parity --chain mainnet --jsonrpc-cors chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn
Database was created with newer client version. Upgrade your client or delete DB and resync.
```

So my clients are upgraded and I am still getting the error message saying "Upgrade your client" (deleting the DB seems extreme when I already upgraded).

Any idea why I am getting this error and how to resolve it?

**Comment by Tbaut** [comment]
>As I run Parity using Parity UI

In this case, there is one important thing to understand is that Metamask and Parity UI are 2 user interface programs that connect to 1 node: Parity Ethereum. 

Parity Ethereum is downloaded automatically and launched when Parity UI is launched. Metamask and Parity UI need a node in the background, but a node does not necessarily need a UI. To make things simple, you do not need Parity UI, and since it is not actively maintained anymore, I'd suggest to try to work with Parity Ethereum (the node) directly through the command line, interface it with metamask, and forget about Parity UI.

The DB problem seems related to the fact that you have had installed Parity Ethereum v2.0 at some point. I'd advise you to install Parity Ethreum v2 (as stated in your first post), launch it with the command line and the relevant flags, and git Metamask connected.

Feel free to pass by our [Gitter chat](https://gitter.im/paritytech/parity) if you need any more clarification.
