### ISSUE TITLE
Clean codebase

### ISSUE THREAD

**Issue by amaurymartiny** [parity-js/shell#92]
Some ideas for removing deprecated stuff in the codebase:

- After https://github.com/paritytech/parity/pull/8539 gets merged, we won't be able to use Parity UI in the browser anymore. We can remove all `<iframes>`, `if (isElectron())`...
- Remove all Rust files
- Use yarn.lock instead of package-lock.json?

**Comment by axelchalon** [comment]
### Misc dapps stuff

In an effort to move all things dapps into the shell and away from Parity:
- [ ] Move built-in dapps info from `@parity/shared` to `@parity/shell`: remove [this folder from `@parity/shared`]( https://github.com/parity-js/shared/tree/master/src/config) and instead have a JSON file in `@parity/shell` with the built-in dapps info.
- [ ] Remove the distinction between `builtin` dapps and `views` dapps (in `@parity/shell` and `@parity/ui`): both should be called `builtin` dapps.
- [ ] We would have three types of dapps: local (located in `.config/io.parity.ethereum/dapps`; thy are either built locally or served in development mode on a specific port by webpack), network (served by Parity from the registry), builtin (default dapps built into the shell). Document this (wiki), as well as the script injection and dapp development workflow (localUrl, etc.).
- [ ] Update `@parity/ui DappIcon` to serve the dapp icons locally using file:// for built-in/local dapps (fixes https://github.com/parity-js/dapp-develop/issues/3)
- [ ] The shell should serve local dapps directly using `file://` instead of accessing them through Parity (the shell should also honor `localUrl` in the manifest.json)
- [ ] Once done, remove shell dependency from Parity and remove Rust files from shell
- [ ] Handle Parity Wallet like any other dapp; it should not be served by Parity but be built into the shell
- [ ] Remove `parity ui` completely as dapps do not work in the browser anymore since https://github.com/paritytech/parity/pull/8539
- [ ] Once done, remove browser-specific code from shell

Built-in and local dapps should be completely handled by the shell; Parity should play no role.
Network dapps require a bit more work.

**Comment by amaurymartiny** [comment]
Excellent summary.

cc @jacogr

**Comment by axelchalon** [comment]
Some documentation in the wiki about the way dapps work now would be nice. (no need to inclure inject.js anymore ; local dapps location ; dapp development experience)

**Comment by amaurymartiny** [comment]
I unchecked `Once done, remove browser-specific code from shell`.

There are a couple of `isElectron()` that could be removed. Also, iframes can be removed.
